using Godot;
using GArray = Godot.Collections.Array;
using GDictionary = Godot.Collections.Dictionary;
using GStringNameArray = Godot.Collections.Array<Godot.StringName>;
using GVector2IArray = Godot.Collections.Array<Godot.Vector2I>;

public interface IGameRuntimeSnapshotSource
{
    bool IsBattleActive();
    string GetStatusText();
    string GetActiveModalId();
    RuntimeModalKind GetActiveModalKind();
    GDictionary GetLogSnapshot(int limit);
    GDictionary GetSelectedSettlement();
    GDictionary GetSelectedWorldNpc();
    EncounterAnchorData GetSelectedEncounterAnchor();
    GDictionary GetSelectedWorldEvent();
    GArray GetNearbyEncounterEntries(int limit);
    GArray GetNearbyWorldEventEntries(int limit);
    string GetActiveMapId();
    string GetActiveMapDisplayName();
    bool IsSubmapActive();
    int GetWorldStep();
    Vector2I GetPlayerCoord();
    bool IsPlayerVisibleOnWorldMap();
    Vector2I GetSelectedCoord();
    GDictionary GetPendingSubmapPrompt();
    string GetSubmapReturnHintText();
    GDictionary GetGameOverContext();
    PartyState GetPartyState();
    StringName GetPartySelectedMemberId();
    int GetPendingRewardCount();
    GDictionary GetMemberAchievementSummary(StringName member_id);
    AttributeSnapshot GetMemberAttributeSnapshot(StringName member_id);
    GArray GetMemberEquippedEntries(StringName member_id);
    string GetMemberDisplayName(StringName member_id);
    string GetResolvedSettlementId();
    GDictionary GetSettlementWindowData(string settlement_id);
    string GetSettlementFeedbackText();
    GDictionary GetShopWindowData();
    GDictionary GetContractBoardWindowData();
    GDictionary GetActiveContractBoardContext();
    GDictionary GetNpcQuestOfferWindowData();
    GDictionary GetActiveNpcQuestOfferContext();
    GDictionary GetActiveShopContext();
    GDictionary GetForgeWindowData();
    GDictionary GetStagecoachWindowData();
    GDictionary GetCharacterInfoContext();
    string GetActiveWarehouseEntryLabel();
    GDictionary GetWarehouseWindowData();
    ContingencySetupMutationResult GetLastContingencyCommandResultTyped();
    BattleState GetBattleState();
    BattleRuntimeModule GetBattleRuntime();
    Vector2I GetBattleSelectedCoord();
    StringName GetSelectedBattleSkillEntryId();
    StringName GetSelectedBattleSkillId();
    StringName GetSelectedBattleSkillVariantId();
    string GetSelectedBattleSkillName();
    string GetSelectedBattleSkillVariantName();
    GVector2IArray GetSelectedBattleSkillTargetCoords();
    GStringNameArray GetSelectedBattleSkillTargetUnitIds();
    int GetSelectedBattleSkillRequiredCoordCount();
    BattlePreview GetSelectedBattleSkillPreview();
    StringName GetActiveBattleEncounterId();
    string GetActiveBattleEncounterName();
    string GetBattleActiveUnitName();
    GDictionary GetPendingBattleStartPrompt();
    GDictionary GetBattleTerrainCounts();
    PendingCharacterReward GetSnapshotReward();
    GDictionary GetLastBattleLootSnapshot();
    GDictionary GetCurrentPromotionPrompt();
    GameSession GetGameSession();
}
