using Godot;
using GArray = Godot.Collections.Array;
using GDictionary = Godot.Collections.Dictionary;
using GStringNameArray = Godot.Collections.Array<Godot.StringName>;
using GVector2IArray = Godot.Collections.Array<Godot.Vector2I>;

public interface IGameRuntimeSnapshotSource
{
    bool is_battle_active();
    string get_status_text();
    string get_active_modal_id();
    GDictionary get_log_snapshot(int limit);
    GDictionary get_selected_settlement();
    GDictionary get_selected_world_npc();
    EncounterAnchorData get_selected_encounter_anchor();
    GDictionary get_selected_world_event();
    GArray get_nearby_encounter_entries(int limit);
    GArray get_nearby_world_event_entries(int limit);
    string get_active_map_id();
    string get_active_map_display_name();
    bool is_submap_active();
    int get_world_step();
    Vector2I get_player_coord();
    bool is_player_visible_on_world_map();
    Vector2I get_selected_coord();
    GDictionary get_pending_submap_prompt();
    string get_submap_return_hint_text();
    GDictionary get_game_over_context();
    PartyState get_party_state();
    StringName get_party_selected_member_id();
    int get_pending_reward_count();
    GDictionary get_member_achievement_summary(StringName member_id);
    AttributeSnapshot get_member_attribute_snapshot(StringName member_id);
    GArray get_member_equipped_entries(StringName member_id);
    string get_member_display_name(StringName member_id);
    string get_resolved_settlement_id();
    GDictionary get_settlement_window_data(string settlement_id);
    string get_settlement_feedback_text();
    GDictionary get_shop_window_data();
    GDictionary get_contract_board_window_data();
    GDictionary get_active_contract_board_context();
    GDictionary get_active_shop_context();
    GDictionary get_forge_window_data();
    GDictionary get_stagecoach_window_data();
    GDictionary get_character_info_context();
    string get_active_warehouse_entry_label();
    GDictionary get_warehouse_window_data();
    BattleState get_battle_state();
    BattleRuntimeModule get_battle_runtime();
    Vector2I get_battle_selected_coord();
    StringName get_selected_battle_skill_id();
    StringName get_selected_battle_skill_variant_id();
    string get_selected_battle_skill_name();
    string get_selected_battle_skill_variant_name();
    GVector2IArray get_selected_battle_skill_target_coords();
    GStringNameArray get_selected_battle_skill_target_unit_ids();
    int get_selected_battle_skill_required_coord_count();
    StringName get_active_battle_encounter_id();
    string get_active_battle_encounter_name();
    string get_battle_active_unit_name();
    GDictionary get_pending_battle_start_prompt();
    GDictionary get_battle_terrain_counts();
    PendingCharacterReward get_snapshot_reward();
    GDictionary get_last_battle_loot_snapshot();
    GDictionary get_current_promotion_prompt();
    GameSession get_game_session();
}
