using Godot;

[GlobalClass]
public partial class ProfessionRuleService : RefCounted
{
    private GodotObject _unit_progress;
    private Godot.Collections.Dictionary _skill_defs = new();
    private Godot.Collections.Dictionary _profession_defs = new();

    public void setup(GodotObject unitProgress, Variant skillDefs, Variant professionDefs) { _unit_progress = unitProgress; _skill_defs = _index_skill_defs(skillDefs); _profession_defs = _index_profession_defs(professionDefs); }

    public bool is_profession_knowledge_unlocked(StringName professionId) { var pd = _get_profession_def(professionId); if (pd == null || !pd.requires_knowledge_unlock()) return pd != null; return _unit_progress?.Call("has_knowledge", pd.unlock_knowledge_id).AsBool() ?? false; }

    public bool can_unlock_profession(StringName professionId) { var pd = _get_profession_def(professionId); if (pd == null || !is_profession_knowledge_unlocked(professionId)) return false; var pp = _get_profession_progress(professionId); if (pp != null && pp.Get("rank").AsInt32() > 0) return false; var ur = pd.unlock_requirement; if (ur == null) return true; if (!_can_satisfy_required_skill_ids_for_unlock(professionId, ur.required_skill_ids)) return false; if (!_can_satisfy_tag_rules_for_unlock(professionId, ur.required_tag_rules)) return false; if (!can_satisfy_profession_gates(ur.required_profession_ranks)) return false; if (!can_satisfy_attribute_rules(ur.required_attribute_rules)) return false; if (!can_satisfy_reputation_rules(ur.required_reputation_rules)) return false; return true; }

    public bool can_rank_up_profession(StringName professionId) { var pd = _get_profession_def(professionId); if (pd == null || !is_profession_knowledge_unlocked(professionId)) return false; var pp = _get_profession_progress(professionId); if (pp == null || pp.Get("rank").AsInt32() <= 0) return false; if (pp.Get("rank").AsInt32() >= pd.max_rank) return false; if (!pp.Get("is_active").AsBool() || pp.Get("is_hidden").AsBool()) return false; var nextReqs = pd.get_rank_requirement(pp.Get("rank").AsInt32() + 1); if (nextReqs == null) return true; if (!_can_satisfy_profession_rank_requirements(professionId, nextReqs.target_rank)) return false; if (!can_satisfy_profession_gates(nextReqs.required_profession_ranks)) return false; return true; }

    public bool can_satisfy_profession_gates(Godot.Collections.Array<ProfessionRankGate> gates) { if (gates.Count == 0) return true; foreach (var g in gates) { if (g == null) continue; var pp = _get_profession_progress(g.profession_id); if (pp == null || pp.Get("rank").AsInt32() < g.min_rank) return false; } return true; }

    public bool can_satisfy_attribute_rules(Godot.Collections.Array<AttributeRequirement> rules) { if (rules.Count == 0) return true; var uba = _unit_progress?.Get("unit_base_attributes").AsGodotObject(); if (uba == null) return false; foreach (var r in rules) { if (r == null) continue; if (uba.Call("get_attribute_value", r.attribute_id).AsInt32() < r.min_value) return false; } return true; }

    public bool can_satisfy_reputation_rules(Godot.Collections.Array<ReputationRequirement> rules) { if (rules.Count == 0) return true; var urs = _unit_progress?.Get("unit_reputation_state").AsGodotObject(); if (urs == null) return false; foreach (var r in rules) { if (r == null) continue; if (urs.Call("get_reputation_value", r.state_id).AsInt32() < r.min_value) return false; } return true; }

    public ProfessionDef _get_profession_def(StringName pid) => _profession_defs.ContainsKey(pid) ? _profession_defs[pid].AsGodotObject() as ProfessionDef : null;
    private GodotObject _get_profession_progress(StringName pid) => _unit_progress?.Call("get_profession_progress", pid).AsGodotObject();

    private bool _can_satisfy_required_skill_ids_for_unlock(StringName pid, Godot.Collections.Array<StringName> requiredIds) { if (requiredIds.Count == 0) return true; foreach (var sid in requiredIds) { if (sid == "" || _unit_progress.Call("get_skill_progress", sid).AsGodotObject() == null) return false; } return true; }

    private bool _can_satisfy_tag_rules_for_unlock(StringName pid, Godot.Collections.Array<TagRequirement> tagRules) { if (tagRules.Count == 0) return true; var skills = _unit_progress.Get("skills").AsGodotDictionary(); var learned = new Godot.Collections.Array<StringName>(); foreach (var sk in skills.Keys) { var sp = skills[sk].AsGodotObject(); if (sp != null && sp.Get("is_learned").AsBool()) learned.Add(sp.Get("skill_id").AsStringName()); } foreach (var tr in tagRules) { if (tr == null) continue; string ns = (string)tr.get_normalized_skill_state(); string no = (string)tr.get_normalized_origin_filter(); string nr = (string)tr.get_normalized_selection_role(); int count = 0; foreach (var sid in learned) { var sp = skills.ContainsKey(sid) ? skills[sid].AsGodotObject() : null; if (sp == null) continue; bool stateOk = ns == "core_max" ? (sp.Get("is_learned").AsBool() && sp.Get("is_core").AsBool() && SkillEffectiveMaxLevelRules.is_at_effective_max_level(_skill_defs.ContainsKey(sid) ? _skill_defs[sid].AsGodotObject() : null, Variant.From(sp), _unit_progress)) : (ns == "core" ? sp.Get("is_core").AsBool() : sp.Get("is_learned").AsBool()); if (!stateOk) continue; if (no == "unmerged_only" && sp.Get("merged_from_skill_ids").AsGodotArray().Count > 0) continue; if (no == "merged_only" && sp.Get("merged_from_skill_ids").AsGodotArray().Count == 0) continue; if (nr == "qualifier" && sp.Get("is_core").AsBool()) continue; if (nr == "assigned_core" && !sp.Get("is_core").AsBool()) continue; if (tr.tag != "" && !_skill_defs.ContainsKey(sid)) continue; if (tr.tag != "") { var sd = _skill_defs[sid].AsGodotObject() as SkillDef; if (sd == null || !sd.tags.Contains(tr.tag)) continue; } count++; } if (count < tr.count) return false; } return true; }

    private bool _can_satisfy_profession_rank_requirements(StringName pid, int targetRank) { var pd = _get_profession_def(pid); if (pd == null) return false; var rankReqs = pd.get_rank_requirement(targetRank); if (rankReqs == null) return true; if (rankReqs.required_tag_rules.Count > 0 && !_can_satisfy_tag_rules_for_unlock(pid, rankReqs.required_tag_rules)) return false; if (!can_satisfy_profession_gates(rankReqs.required_profession_ranks)) return false; if (!can_satisfy_attribute_rules(rankReqs.required_attribute_rules)) return false; if (!can_satisfy_reputation_rules(rankReqs.required_reputation_rules)) return false; return true; }

    private Godot.Collections.Dictionary _index_skill_defs(Variant skillDefs) { var r = new Godot.Collections.Dictionary(); if (skillDefs.VariantType == Variant.Type.Dictionary) foreach (var k in skillDefs.AsGodotDictionary().Keys) { var sd = skillDefs.AsGodotDictionary()[k].AsGodotObject() as SkillDef; if (sd != null) { var id = sd.skill_id != "" ? sd.skill_id : ProgressionDataUtils.to_string_name(k); r[id] = sd; } } else if (skillDefs.VariantType == Variant.Type.Array) foreach (var sv in skillDefs.AsGodotArray()) { var sd = sv.AsGodotObject() as SkillDef; if (sd != null && sd.skill_id != "") r[sd.skill_id] = sd; } return r; }

    private Godot.Collections.Dictionary _index_profession_defs(Variant profDefs) { var r = new Godot.Collections.Dictionary(); if (profDefs.VariantType == Variant.Type.Dictionary) foreach (var k in profDefs.AsGodotDictionary().Keys) { var pd = profDefs.AsGodotDictionary()[k].AsGodotObject() as ProfessionDef; if (pd != null) { var id = pd.profession_id != "" ? pd.profession_id : ProgressionDataUtils.to_string_name(k); r[id] = pd; } } else if (profDefs.VariantType == Variant.Type.Array) foreach (var pv in profDefs.AsGodotArray()) { var pd = pv.AsGodotObject() as ProfessionDef; if (pd != null && pd.profession_id != "") r[pd.profession_id] = pd; } return r; }
}
