using Godot;

[GlobalClass]
public partial class PartyWarehouseService : RefCounted
{
    private static readonly StringName STORAGE_SPACE_ATTRIBUTE_ID = "storage_space";
    private PartyState _party_state = new PartyState();
    private Godot.Collections.Dictionary _item_defs = new();
    private WarehouseState _party_backpack_view;
    private Callable _equipment_instance_id_allocator;
    private int _local_equipment_instance_serial = 1;

    public void setup(PartyState ps, Godot.Collections.Dictionary itemDefs = null, Callable eidAlloc = default) { _party_state = ps ?? new PartyState(); _item_defs = itemDefs ?? new Godot.Collections.Dictionary(); _party_backpack_view = null; _equipment_instance_id_allocator = eidAlloc; }
    public void setup_party_backpack_view(PartyState ps, WarehouseState pbv, Godot.Collections.Dictionary itemDefs = null, Callable eidAlloc = default) { _party_state = ps ?? new PartyState(); _item_defs = itemDefs ?? new Godot.Collections.Dictionary(); _party_backpack_view = pbv ?? new WarehouseState(); _equipment_instance_id_allocator = eidAlloc; }

    public int get_total_capacity() { if (_party_state == null) return 0; int tc = 0; foreach (var msv in _party_state.member_states.Values) { var ms = msv.AsGodotObject() as PartyMemberState; if (ms?.progression == null) continue; var uba = ms.progression.Get("unit_base_attributes").AsGodotObject() as UnitBaseAttributes; if (uba != null) tc += Mathf.Max(uba.get_attribute_value(STORAGE_SPACE_ATTRIBUTE_ID), 0); } return Mathf.Max(tc, 0); }
    public int get_used_slots() { var ws = _get_warehouse_state(); return ws.get_non_empty_stacks().Count + ws.get_non_empty_instances().Count; }
    public int get_free_slots() => Mathf.Max(get_total_capacity() - get_used_slots(), 0);
    public bool is_over_capacity() => get_used_slots() > get_total_capacity();

    public int count_item(StringName itemId) { var ni = ProgressionDataUtils.to_string_name(itemId); if (ni == "") return 0; int tq = 0; var ws = _get_warehouse_state(); foreach (var s in ws.get_non_empty_stacks()) { if (s.AsGodotObject().Get("item_id").AsStringName() != ni) continue; tq += Mathf.Max(s.AsGodotObject().Get("quantity").AsInt32(), 0); } foreach (var i in ws.get_non_empty_instances()) { if (i.AsGodotObject().Get("item_id").AsStringName() == ni) tq += 1; } return tq; }
    public Godot.Collections.Array get_stacks() => _get_warehouse_state().duplicate_state().stacks;

    public Godot.Collections.Array<Godot.Collections.Dictionary> get_inventory_entries() { var wh = _get_warehouse_state().duplicate_state(); var entries = new Godot.Collections.Array<Godot.Collections.Dictionary>(); foreach (var s in wh.get_non_empty_stacks()) { var so = s.AsGodotObject(); if (so == null || (bool)so.Call("is_empty")) continue; entries.Add(_build_inventory_entry(so.Get("item_id").AsStringName(), so.Get("quantity").AsInt32(), "stack")); } var ee = new System.Collections.Generic.List<Godot.Collections.Dictionary>(); foreach (var i in wh.get_non_empty_instances()) { var io = i.AsGodotObject(); if (io == null || io.Get("item_id").AsStringName() == "") continue; ee.Add(_build_inventory_entry(io.Get("item_id").AsStringName(), 1, "instance", io)); } ee.Sort((a, b) => string.CompareOrdinal($"{a["item_id"]}:{a.GetValueOrDefault("instance_id","")}", $"{b["item_id"]}:{b.GetValueOrDefault("instance_id","")}")); foreach (var e in ee) entries.Add(e); return entries; }

    public ItemDef get_item_def(StringName itemId) { var ni = ProgressionDataUtils.to_string_name(itemId); return _item_defs.ContainsKey(ni) ? _item_defs[ni].AsGodotObject() as ItemDef : null; }
    public Godot.Collections.Dictionary preview_add_item(StringName itemId, int qty) => _process_add(itemId, qty, false, false);
    public Godot.Collections.Dictionary add_item(StringName itemId, int qty) => _process_add(itemId, qty, true, true);

    public Godot.Collections.Dictionary remove_item(StringName itemId, int qty) { var ni = ProgressionDataUtils.to_string_name(itemId); int rq = Mathf.Max(qty, 0); var wh = _ensure_warehouse_state(); _compact_state(wh); int usb = get_used_slots(); if (ni == "" || rq <= 0) return _rmr(ni, rq, 0, rq, usb, usb, ""); int rem = rq; var id = get_item_def(ni); if (id != null && id.is_equipment()) { var mi = _find_equipment_instance_indexes_by_item(wh, ni); if (rq == 1 && mi.Count == 1) { wh.equipment_instances.RemoveAt(mi[0]); rem = 0; } else { int usa = get_used_slots(); return _rmr(ni, rq, 0, rq, usb, usa, "equipment_instance_id_required"); } } else { for (int i = wh.stacks.Count - 1; i >= 0 && rem > 0; i--) { var sv = wh.stacks[i]; var so = sv.AsGodotObject(); if (so == null || so.Get("item_id").AsStringName() != ni) continue; int rq2 = Mathf.Min(Mathf.Max(so.Get("quantity").AsInt32(), 0), rem); so.Set("quantity", so.Get("quantity").AsInt32() - rq2); rem -= rq2; if (so.Get("quantity").AsInt32() <= 0) wh.stacks.RemoveAt(i); } } _compact_state(wh); int usa2 = get_used_slots(); return _rmr(ni, rq, rq - rem, rem, usb, usa2, ""); }

    public Godot.Collections.Dictionary preview_batch_swap(Godot.Collections.Array<StringName> w, Godot.Collections.Array<StringName> d) => _run_batch_swap_transaction(Variant.From(w).AsGodotArray(), Variant.From(d).AsGodotArray(), false);
    public Godot.Collections.Dictionary commit_batch_swap(Godot.Collections.Array<StringName> w, Godot.Collections.Array<StringName> d) => _run_batch_swap_transaction(new Godot.Collections.Array(w), Variant.From(d).AsGodotArray(), true);
    public Godot.Collections.Dictionary preview_batch_swap_entries(Godot.Collections.Array w, Godot.Collections.Array d) => _run_batch_swap_transaction(w, d, false);
    public Godot.Collections.Dictionary commit_batch_swap_entries(Godot.Collections.Array w, Godot.Collections.Array d) => _run_batch_swap_transaction(w, d, true);

    public GodotObject get_equipment_instance_by_id(StringName iid, StringName eid = default) { var ni = ProgressionDataUtils.to_string_name(iid); var ne = ProgressionDataUtils.to_string_name(eid); if (ne == "") return null; foreach (var iv in _get_warehouse_state().get_non_empty_instances()) { var io = iv.AsGodotObject(); if (io == null || ProgressionDataUtils.to_string_name(io.Get("instance_id")) != ne) continue; if (ne != "" && ProgressionDataUtils.to_string_name(io.Get("item_id")) != ne) return null; return EquipmentInstanceState.from_dict(io.Call("to_dict")); } return null; }
    public bool has_equipment_instance(StringName iid, StringName eid = default) => get_equipment_instance_by_id(iid, eid) != null;

    public GodotObject take_equipment_instance_by_item(StringName iid) { var n = ProgressionDataUtils.to_string_name(iid); var wh = _ensure_warehouse_state(); var mi = _find_equipment_instance_indexes_by_item(wh, n); if (mi.Count != 1) return null; int idx = mi[0]; var inst = wh.equipment_instances[idx]; wh.equipment_instances.RemoveAt(idx); return inst.AsGodotObject(); }
    public GodotObject take_equipment_instance_by_instance_id(StringName iid, StringName eid = default) { var ni = ProgressionDataUtils.to_string_name(iid); var ne = ProgressionDataUtils.to_string_name(eid); if (ne == "") return null; var wh = _ensure_warehouse_state(); for (int i = 0; i < wh.equipment_instances.Count; i++) { var io = wh.equipment_instances[i].AsGodotObject(); if (io == null || ProgressionDataUtils.to_string_name(io.Get("instance_id")) != ne) continue; if (ni != "" && ProgressionDataUtils.to_string_name(io.Get("item_id")) != ni) return null; wh.equipment_instances.RemoveAt(i); return io; } return null; }

    public Godot.Collections.Dictionary remove_equipment_instance(StringName iid, StringName instId) { var ni = ProgressionDataUtils.to_string_name(iid); var nii = ProgressionDataUtils.to_string_name(instId); var wh = _ensure_warehouse_state(); _compact_state(wh); int usb = get_used_slots(); var id = get_item_def(ni); if (ni == "" || id == null) { var r = _rmr2(ni, nii, 0, 1, usb, usb); r["error_code"] = "item_not_found"; return r; } if (!id.is_equipment()) { var r = _rmr2(ni, nii, 0, 1, usb, usb); r["error_code"] = "item_not_equipment"; return r; } if (nii == "") { var r = _rmr2(ni, nii, 0, 1, usb, usb); r["error_code"] = "equipment_instance_id_required"; return r; } bool matched = false; foreach (var iv in wh.get_non_empty_instances()) { var io = iv.AsGodotObject(); if (io == null || ProgressionDataUtils.to_string_name(io.Get("instance_id")) != nii) continue; matched = true; if (ProgressionDataUtils.to_string_name(io.Get("item_id")) != ni) { var r = _rmr2(ni, nii, 0, 1, usb, usb); r["error_code"] = "equipment_instance_item_mismatch"; return r; } break; } if (!matched) { var r = _rmr2(ni, nii, 0, 1, usb, usb); r["error_code"] = "warehouse_missing_instance"; return r; } var ri = take_equipment_instance_by_instance_id(nii, ni); if (ri == null) { var r = _rmr2(ni, nii, 0, 1, usb, usb); r["error_code"] = "warehouse_missing_instance"; return r; } _compact_state(wh); int usa = get_used_slots(); return _rmr2(ni, nii, 1, 0, usb, usa); }

    public Godot.Collections.Dictionary add_equipment_instance(GodotObject inst, bool forceNewId = false) { var wh = _ensure_warehouse_state(); _compact_state(wh); int usb = get_used_slots(); var iid = ProgressionDataUtils.to_string_name(inst?.Get("item_id") ?? ""); var id = get_item_def(iid); var r = new Godot.Collections.Dictionary { {"item_id",(string)iid},{"requested_quantity",1},{"added_quantity",0},{"remaining_quantity",1},{"used_slots_before",usb},{"used_slots_after",usb},{"free_slots_after",Mathf.Max(get_total_capacity()-usb,0)},{"is_over_capacity",usb>get_total_capacity()},{"item_found",id!=null},{"is_equipment",id!=null&&id.is_equipment()},{"allocated_equipment_instance_ids",new Godot.Collections.Array<string>()} }; if (inst == null || iid == "" || id == null || !id.is_equipment()) return r; if (get_total_capacity() - usb <= 0) return r; string aid = ""; if (forceNewId || inst.Get("instance_id").AsStringName() == "") { aid = (string)_allocate_equipment_instance_id(wh); inst.Set("instance_id", new StringName(aid)); if (aid == "") return r; } wh.equipment_instances.Add(inst); _compact_state(wh); int usa = get_used_slots(); r["added_quantity"] = 1; r["remaining_quantity"] = 0; r["used_slots_after"] = usa; r["free_slots_after"] = Mathf.Max(get_total_capacity() - usa, 0); r["is_over_capacity"] = usa > get_total_capacity(); if (aid != "") r["allocated_equipment_instance_ids"] = new Godot.Collections.Array<string> { aid }; return r; }
    public bool deposit_equipment_instance(GodotObject inst) { if (inst == null) return false; var wh = _ensure_warehouse_state(); if (inst.Get("instance_id").AsStringName() == "") { var aid = _allocate_equipment_instance_id(wh); inst.Set("instance_id", aid); if (aid == "") return false; } wh.equipment_instances.Add(inst); return true; }

    private Godot.Collections.Dictionary _execute_batch_swap(Godot.Collections.Array w, Godot.Collections.Array d, bool consumeAlloc) { foreach (var wv in w) { var we = _normalize_batch_item_entry(wv); var iid = ProgressionDataUtils.to_string_name(we.ContainsKey("item_id")?we["item_id"]:""); var instId = ProgressionDataUtils.to_string_name(we.ContainsKey("instance_id")?we["instance_id"]:""); var id = get_item_def(iid); Godot.Collections.Dictionary r; if (id != null && id.is_equipment() && instId != "") r = remove_equipment_instance(iid, instId); else r = remove_item(iid, 1); if (r.ContainsKey("removed_quantity") && r["removed_quantity"].AsInt32() <= 0) return new Godot.Collections.Dictionary { {"allowed",false},{"error_code",r.ContainsKey("error_code")&&r["error_code"].AsString().Length>0?r["error_code"].AsString():"warehouse_missing_item"},{"blocked_item_id",(string)iid},{"blocked_instance_id",(string)instId} }; } foreach (var dv in d) { var de = _normalize_batch_item_entry(dv); var iid2 = ProgressionDataUtils.to_string_name(de.ContainsKey("item_id")?de["item_id"]:""); var pv = preview_add_item(iid2, 1); if (pv.ContainsKey("remaining_quantity") && pv["remaining_quantity"].AsInt32() > 0) return new Godot.Collections.Dictionary { {"allowed",false},{"error_code","warehouse_blocked_swap"},{"blocked_item_id",(string)iid2},{"blocked_instance_id",(string)ProgressionDataUtils.to_string_name(de.ContainsKey("instance_id")?de["instance_id"]:"")} }; var eiv = de.ContainsKey("equipment_instance") ? de["equipment_instance"] : default(Variant); if (eiv.VariantType != Variant.Type.Nil) { var inst = eiv.AsGodotObject(); if (eiv.VariantType == Variant.Type.Dictionary) inst = EquipmentInstanceState.from_dict(eiv); var air = add_equipment_instance(inst, false); if (air.ContainsKey("added_quantity") && air["added_quantity"].AsInt32() <= 0) return new Godot.Collections.Dictionary { {"allowed",false},{"error_code",air.ContainsKey("error_code")?air["error_code"].AsString():"warehouse_blocked_swap"},{"blocked_item_id",(string)iid2},{"blocked_instance_id",(string)ProgressionDataUtils.to_string_name(de.ContainsKey("instance_id")?de["instance_id"]:"")} }; } else _process_add(iid2, 1, true, consumeAlloc); } return new Godot.Collections.Dictionary { {"allowed",true},{"error_code",""},{"blocked_item_id",""},{"blocked_instance_id",""} }; }

    private Godot.Collections.Dictionary _run_batch_swap_transaction(Godot.Collections.Array w, Godot.Collections.Array d, bool commit) { var bl = _get_warehouse_state().duplicate_state(); if (_party_state == null) _party_state = new PartyState(); var orig = _party_backpack_view ?? _party_state.warehouse_state; _set_transaction_warehouse_state(bl); var r = _execute_batch_swap(w, d, commit); if (r.ContainsKey("allowed") && r["allowed"].AsBool() && commit) { if (_party_backpack_view != null) { _copy_warehouse_state(bl, orig); _party_backpack_view = orig; } return r; } _set_transaction_warehouse_state(orig); return r; }

    private static Godot.Collections.Dictionary _normalize_batch_item_entry(Variant ev) { if (ev.VariantType == Variant.Type.Dictionary) { var e = ev.AsGodotDictionary(); var r = new Godot.Collections.Dictionary { {"item_id",ProgressionDataUtils.to_string_name(e.ContainsKey("item_id")?e["item_id"]:"")},{"instance_id",ProgressionDataUtils.to_string_name(e.ContainsKey("instance_id")?e["instance_id"]:"")} }; if (e.ContainsKey("equipment_instance")) r["equipment_instance"] = e["equipment_instance"]; return r; } return new Godot.Collections.Dictionary { {"item_id",ProgressionDataUtils.to_string_name(ev)},{"instance_id",new StringName("")} }; }

    private Godot.Collections.Dictionary _process_add(StringName iid, int qty, bool mutate, bool consumeAlloc) { var ni = ProgressionDataUtils.to_string_name(iid); int rq = Mathf.Max(qty, 0), usb = get_used_slots(); var id = get_item_def(ni); var ts = mutate ? _ensure_warehouse_state() : _get_warehouse_state().duplicate_state(); _compact_state(ts); int cu = ts.stacks.Count + ts.get_non_empty_instances().Count; var r = new Godot.Collections.Dictionary { {"item_id",(string)ni},{"requested_quantity",rq},{"added_quantity",0},{"remaining_quantity",rq},{"used_slots_before",usb},{"used_slots_after",cu},{"free_slots_after",Mathf.Max(get_total_capacity()-cu,0)},{"created_stack_count",0},{"filled_existing_quantity",0},{"is_over_capacity",cu>get_total_capacity()},{"item_found",id!=null} }; if (ni == "" || rq <= 0 || id == null) return r; int rem = rq; if (id.is_equipment()) { int av = Mathf.Max(get_total_capacity() - ts.stacks.Count - ts.equipment_instances.Count, 0); int cr = 0; var aids = new Godot.Collections.Array<string>(); while (rem > 0 && av > 0) { var ni2 = _create_equipment_instance(ni, ts, consumeAlloc); if (ni2.Get("instance_id").AsStringName() == "") break; if (consumeAlloc) aids.Add((string)ni2.Get("instance_id").AsStringName()); ts.equipment_instances.Add(ni2); rem--; av--; cr++; } r["created_stack_count"] = cr; r["allocated_equipment_instance_ids"] = aids; } else { int fe = 0, ms = id.get_effective_max_stack(); foreach (var sv in ts.stacks) { if (rem <= 0) break; var so = sv.AsGodotObject(); if (so == null || so.Get("item_id").AsStringName() != ni) continue; if (so.Get("quantity").AsInt32() >= ms) continue; int ac = Mathf.Min(ms - so.Get("quantity").AsInt32(), rem); if (ac <= 0) continue; so.Set("quantity", so.Get("quantity").AsInt32() + ac); rem -= ac; fe += ac; } int cs = 0, ans = Mathf.Max(get_total_capacity() - ts.stacks.Count - ts.equipment_instances.Count, 0); while (rem > 0 && ans > 0) { var ns = new WarehouseStackState { item_id = ni, quantity = Mathf.Min(ms, rem) }; ts.stacks.Add(ns); rem -= ns.quantity; ans--; cs++; } _compact_state(ts); r["filled_existing_quantity"] = fe; r["created_stack_count"] = cs; } int usa = ts.stacks.Count + ts.get_non_empty_instances().Count; r["added_quantity"] = rq - rem; r["remaining_quantity"] = rem; r["used_slots_after"] = usa; r["free_slots_after"] = Mathf.Max(get_total_capacity() - usa, 0); r["is_over_capacity"] = usa > get_total_capacity(); return r; }

    private EquipmentInstanceState _create_equipment_instance(StringName iid, WarehouseState ts, bool consumeAlloc) { var inst = EquipmentInstanceState.create(iid); inst.instance_id = consumeAlloc ? _allocate_equipment_instance_id(ts) : _allocate_preview_equipment_instance_id(ts); return inst; }
    private StringName _allocate_equipment_instance_id(WarehouseState ts = null) { if (!string.IsNullOrEmpty(_equipment_instance_id_allocator.Method)) return ProgressionDataUtils.to_string_name(_equipment_instance_id_allocator.Call()); while (true) { var c = EquipmentInstanceState.format_instance_id(_local_equipment_instance_serial); _local_equipment_instance_serial++; if (!_equipment_instance_id_exists(c, ts)) return c; } }
    private StringName _allocate_preview_equipment_instance_id(WarehouseState ts = null) { int s = 1; while (true) { var c = EquipmentInstanceState.format_preview_instance_id(s); s++; if (!_equipment_instance_id_exists(c, ts)) return c; } }
    private bool _equipment_instance_id_exists(StringName iid, WarehouseState ts = null) { var n = ProgressionDataUtils.to_string_name(iid); if (n == "") return false; var states = new System.Collections.Generic.List<WarehouseState>(); if (ts != null) states.Add(ts); var cs = _get_warehouse_state(); if (cs != null && cs != ts) states.Add(cs); foreach (var st in states) foreach (var iv in st.get_non_empty_instances()) { var io = iv.AsGodotObject(); if (io != null && ProgressionDataUtils.to_string_name(io.Get("instance_id")) == n) return true; } return false; }

    private static Godot.Collections.Array<int> _find_equipment_instance_indexes_by_item(WarehouseState wh, StringName iid) { var r = new Godot.Collections.Array<int>(); if (wh == null) return r; var n = ProgressionDataUtils.to_string_name(iid); for (int i = 0; i < wh.equipment_instances.Count; i++) { var io = wh.equipment_instances[i].AsGodotObject(); if (io != null && ProgressionDataUtils.to_string_name(io.Get("item_id")) == n) r.Add(i); } return r; }

    private WarehouseState _ensure_warehouse_state() { if (_party_backpack_view != null) return _party_backpack_view; if (_party_state == null) _party_state = new PartyState(); if (_party_state.warehouse_state == null) _party_state.warehouse_state = new WarehouseState(); return _party_state.warehouse_state; }
    private WarehouseState _get_warehouse_state() { if (_party_backpack_view != null) return _party_backpack_view; if (_party_state == null) return new WarehouseState(); return _party_state.warehouse_state ?? new WarehouseState(); }
    private void _set_transaction_warehouse_state(WarehouseState wh) { if (_party_backpack_view != null) { _party_backpack_view = wh; return; } if (_party_state == null) _party_state = new PartyState(); _party_state.warehouse_state = wh; }
    private static void _copy_warehouse_state(WarehouseState src, WarehouseState dst) { if (src == null || dst == null) return; dst.stacks.Clear(); dst.equipment_instances.Clear(); foreach (var sv in src.get_non_empty_stacks()) dst.stacks.Add(sv); foreach (var iv in src.get_non_empty_instances()) dst.equipment_instances.Add(EquipmentInstanceState.from_dict(iv.AsGodotObject().Call("to_dict"))); }
    private static void _compact_state(WarehouseState wh) { if (wh == null) return; wh.stacks = wh.get_non_empty_stacks(); wh.equipment_instances = wh.get_non_empty_instances(); }

    private Godot.Collections.Dictionary _build_inventory_entry(StringName iid, int qty, StringName mode, GodotObject ei = null) { var ni = ProgressionDataUtils.to_string_name(iid); int rq = Mathf.Max(qty, 0); var id = get_item_def(ni); var gsid = id?.granted_skill_id ?? new StringName(""); var e = new Godot.Collections.Dictionary { {"item_id",(string)ni},{"display_name",id!=null&&id.display_name.Length>0?id.display_name:(string)ni},{"description",id?.description??"该物品定义缺失，当前仅保留存档中的 item_id 与数量。"},{"icon",id?.icon??""},{"quantity",rq},{"total_quantity",count_item(ni)},{"is_stackable",id?.is_stackable??rq>1},{"stack_limit",id?.get_effective_max_stack()??Mathf.Max(rq,1)},{"item_category",id!=null?(string)id.get_item_category_normalized():""},{"is_skill_book",id!=null&&id.is_skill_book()},{"granted_skill_id",(string)gsid},{"storage_mode",(string)mode} }; if (ei != null) { e["instance_id"] = (string)ProgressionDataUtils.to_string_name(ei.Get("instance_id")); e["rarity"] = ei.Get("rarity").AsInt32(); e["current_durability"] = ei.Get("current_durability").AsInt32(); } return e; }
    private static Godot.Collections.Dictionary _rmr(StringName ni, int rq, int removed, int rem, int usb, int usa, string ec) { return new Godot.Collections.Dictionary { {"item_id",(string)ni},{"requested_quantity",rq},{"removed_quantity",removed},{"remaining_quantity",rem},{"used_slots_before",usb},{"used_slots_after",usa},{"free_slots_after",Mathf.Max(0,0)},{"is_over_capacity",false},{"error_code",ec} }; }
    private Godot.Collections.Dictionary _rmr2(StringName ni, StringName nii, int removed, int rem, int usb, int usa) { return new Godot.Collections.Dictionary { {"item_id",(string)ni},{"instance_id",(string)nii},{"requested_quantity",1},{"removed_quantity",removed},{"remaining_quantity",rem},{"used_slots_before",usb},{"used_slots_after",usa},{"free_slots_after",Mathf.Max(get_total_capacity()-usa,0)},{"is_over_capacity",usa>get_total_capacity()},{"error_code",""} }; }
}

