## 文件说明：该脚本只提供战士技能目录的声明式 spec 数据，不包含 builder 逻辑。
## 审查重点：重点核对 warrior catalog 的 costs、targeting、special effect 与复合升级前置是否完整保留。

class_name DesignSkillCatalogWarriorSpecs
extends RefCounted

const WARRIOR_SKILL_SPECS: Array[Dictionary] = [
	{
		"kind": &"active",
		"skill_id": &"warrior_heavy_strike",
		"display_name": "重击",
		"description": "150% 伤害并附带轻度破甲。",
		"tags": [&"warrior", &"melee", &"output"],
		"costs": {"range_value": 1, "ap_cost": 2, "mp_cost": 0, "stamina_cost": 1, "aura_cost": 0, "cooldown_tu": 1, "hit_rate": 0},
		"targeting": {"target_mode": &"unit", "target_team_filter": &"enemy", "range_pattern": &"single", "area_pattern": &"single", "area_value": 0, "target_selection_mode": &"single_unit", "min_target_count": 1, "max_target_count": 1, "selection_order_mode": &"stable"},
		"mastery_curve": [24, 40, 62],
		"max_level": 3,
		"learn_source": &"book",
		"effect_defs": [
			{"kind": &"damage", "power": 15},
			{"kind": &"status", "status_id": &"armor_break", "duration": 1, "power": 1},
		],
	},
	{
		"kind": &"active",
		"skill_id": &"warrior_sweeping_slash",
		"display_name": "横扫",
		"description": "前方范围横扫。",
		"tags": [&"warrior", &"melee", &"aoe"],
		"costs": {"range_value": 1, "ap_cost": 2, "mp_cost": 0, "stamina_cost": 1, "aura_cost": 0, "cooldown_tu": 1, "hit_rate": 0},
		"targeting": {"target_mode": &"ground", "target_team_filter": &"enemy", "range_pattern": &"single", "area_pattern": &"cone", "area_value": 1, "target_selection_mode": &"single_unit", "min_target_count": 1, "max_target_count": 1, "selection_order_mode": &"stable"},
		"mastery_curve": [24, 40, 62],
		"max_level": 3,
		"learn_source": &"book",
		"effect_defs": [{"kind": &"damage", "power": 12}],
	},
	{
		"kind": &"active",
		"skill_id": &"warrior_piercing_thrust",
		"display_name": "穿刺",
		"description": "直线穿透的突刺技能。",
		"tags": [&"warrior", &"melee", &"thrust"],
		"costs": {"range_value": 2, "ap_cost": 2, "mp_cost": 0, "stamina_cost": 1, "aura_cost": 0, "cooldown_tu": 1, "hit_rate": 0},
		"targeting": {"target_mode": &"ground", "target_team_filter": &"enemy", "range_pattern": &"single", "area_pattern": &"line", "area_value": 2, "target_selection_mode": &"single_unit", "min_target_count": 1, "max_target_count": 1, "selection_order_mode": &"stable"},
		"mastery_curve": [24, 40, 62],
		"max_level": 3,
		"learn_source": &"book",
		"effect_defs": [{"kind": &"damage", "power": 12}],
	},
	{
		"kind": &"active",
		"skill_id": &"warrior_guard_break",
		"display_name": "裂甲斩",
		"description": "用于撕开防御姿态的定点技能。",
		"tags": [&"warrior", &"melee", &"breaker"],
		"costs": {"range_value": 1, "ap_cost": 2, "mp_cost": 0, "stamina_cost": 1, "aura_cost": 0, "cooldown_tu": 2, "hit_rate": 0},
		"targeting": {"target_mode": &"unit", "target_team_filter": &"enemy", "range_pattern": &"single", "area_pattern": &"single", "area_value": 0, "target_selection_mode": &"single_unit", "min_target_count": 1, "max_target_count": 1, "selection_order_mode": &"stable"},
		"mastery_curve": [28, 46, 72],
		"max_level": 3,
		"learn_source": &"book",
		"effect_defs": [
			{"kind": &"damage", "power": 13},
			{"kind": &"status", "status_id": &"armor_break", "duration": 2, "power": 1},
		],
	},
	{
		"kind": &"active",
		"skill_id": &"warrior_execution_cleave",
		"display_name": "断头斩",
		"description": "对低血目标有更高收益的斩杀技。",
		"tags": [&"warrior", &"melee", &"finisher"],
		"costs": {"range_value": 1, "ap_cost": 2, "mp_cost": 0, "stamina_cost": 2, "aura_cost": 0, "cooldown_tu": 2, "hit_rate": 0},
		"targeting": {"target_mode": &"unit", "target_team_filter": &"enemy", "range_pattern": &"single", "area_pattern": &"single", "area_value": 0, "target_selection_mode": &"single_unit", "min_target_count": 1, "max_target_count": 1, "selection_order_mode": &"stable"},
		"mastery_curve": [28, 46, 72],
		"max_level": 3,
		"learn_source": &"book",
		"effect_defs": [
			{"kind": &"damage", "power": 16, "bonus_condition": &"target_low_hp", "damage_ratio_percent": 180},
		],
	},
	{
		"kind": &"active",
		"skill_id": &"warrior_jump_slash",
		"display_name": "跳斩",
		"description": "位移后落地造成小范围伤害。",
		"tags": [&"warrior", &"melee", &"mobility"],
		"costs": {"range_value": 3, "ap_cost": 2, "mp_cost": 0, "stamina_cost": 2, "aura_cost": 0, "cooldown_tu": 2, "hit_rate": 0},
		"targeting": {"target_mode": &"ground", "target_team_filter": &"enemy", "range_pattern": &"single", "area_pattern": &"radius", "area_value": 1, "target_selection_mode": &"single_unit", "min_target_count": 1, "max_target_count": 1, "selection_order_mode": &"stable"},
		"mastery_curve": [28, 46, 72],
		"max_level": 3,
		"learn_source": &"book",
		"effect_defs": [
			{"kind": &"damage", "power": 12},
			{"kind": &"special", "effect_type": &"forced_move", "params": {"mode": "jump"}},
		],
	},
	{
		"kind": &"active",
		"skill_id": &"warrior_backstep",
		"display_name": "后撤步",
		"description": "后退并提升闪避。",
		"tags": [&"warrior", &"melee", &"mobility"],
		"costs": {"range_value": 0, "ap_cost": 1, "mp_cost": 0, "stamina_cost": 1, "aura_cost": 0, "cooldown_tu": 1, "hit_rate": 0},
		"targeting": {"target_mode": &"unit", "target_team_filter": &"ally", "range_pattern": &"single", "area_pattern": &"single", "area_value": 0, "target_selection_mode": &"self", "min_target_count": 1, "max_target_count": 1, "selection_order_mode": &"stable"},
		"mastery_curve": [24, 40, 62],
		"max_level": 3,
		"learn_source": &"book",
		"effect_defs": [{"kind": &"status", "status_id": &"evasion_up", "duration": 1, "power": 1}],
	},
	{
		"kind": &"active",
		"skill_id": &"warrior_guard",
		"display_name": "格挡",
		"description": "显著降低承受伤害。",
		"tags": [&"warrior", &"melee", &"defense"],
		"costs": {"range_value": 0, "ap_cost": 1, "mp_cost": 0, "stamina_cost": 1, "aura_cost": 0, "cooldown_tu": 2, "hit_rate": 0},
		"targeting": {"target_mode": &"unit", "target_team_filter": &"ally", "range_pattern": &"single", "area_pattern": &"single", "area_value": 0, "target_selection_mode": &"self", "min_target_count": 1, "max_target_count": 1, "selection_order_mode": &"stable"},
		"mastery_curve": [24, 40, 62],
		"max_level": 3,
		"learn_source": &"book",
		"effect_defs": [
			{"kind": &"status", "status_id": &"guarding", "duration": 1, "power": 1},
			{"kind": &"status", "status_id": &"damage_reduction_up", "duration": 1, "power": 1},
		],
	},
	{
		"kind": &"active",
		"skill_id": &"warrior_shield_wall",
		"display_name": "护盾墙",
		"description": "为自身周围友军提供群体减伤。",
		"tags": [&"warrior", &"melee", &"defense"],
		"costs": {"range_value": 0, "ap_cost": 2, "mp_cost": 0, "stamina_cost": 2, "aura_cost": 0, "cooldown_tu": 2, "hit_rate": 0},
		"targeting": {"target_mode": &"ground", "target_team_filter": &"ally", "range_pattern": &"single", "area_pattern": &"radius", "area_value": 1, "target_selection_mode": &"single_unit", "min_target_count": 1, "max_target_count": 1, "selection_order_mode": &"stable"},
		"mastery_curve": [28, 46, 72],
		"max_level": 3,
		"learn_source": &"book",
		"effect_defs": [{"kind": &"status", "status_id": &"damage_reduction_up", "duration": 1, "power": 1, "effect_target_team_filter": &"ally"}],
	},
	{
		"kind": &"active",
		"skill_id": &"warrior_battle_recovery",
		"display_name": "战斗回复",
		"description": "稳定恢复自身生命。",
		"tags": [&"warrior", &"melee", &"recovery"],
		"costs": {"range_value": 0, "ap_cost": 1, "mp_cost": 0, "stamina_cost": 1, "aura_cost": 0, "cooldown_tu": 2, "hit_rate": 0},
		"targeting": {"target_mode": &"unit", "target_team_filter": &"ally", "range_pattern": &"single", "area_pattern": &"single", "area_value": 0, "target_selection_mode": &"self", "min_target_count": 1, "max_target_count": 1, "selection_order_mode": &"stable"},
		"mastery_curve": [24, 40, 62],
		"max_level": 3,
		"learn_source": &"book",
		"effect_defs": [{"kind": &"heal", "power": 10, "effect_target_team_filter": &"ally"}],
	},
	{
		"kind": &"active",
		"skill_id": &"warrior_shield_bash",
		"display_name": "盾击",
		"description": "近身控制技。",
		"tags": [&"warrior", &"melee", &"control", &"shield"],
		"costs": {"range_value": 1, "ap_cost": 1, "mp_cost": 0, "stamina_cost": 1, "aura_cost": 0, "cooldown_tu": 2, "hit_rate": 0},
		"targeting": {"target_mode": &"unit", "target_team_filter": &"enemy", "range_pattern": &"single", "area_pattern": &"single", "area_value": 0, "target_selection_mode": &"single_unit", "min_target_count": 1, "max_target_count": 1, "selection_order_mode": &"stable"},
		"mastery_curve": [24, 40, 62],
		"max_level": 3,
		"learn_source": &"book",
		"effect_defs": [
			{"kind": &"damage", "power": 11},
			{"kind": &"status", "status_id": &"staggered", "duration": 1, "power": 1},
		],
	},
	{
		"kind": &"active",
		"skill_id": &"warrior_taunt",
		"display_name": "挑衅",
		"description": "迫使敌人优先关注自己。",
		"tags": [&"warrior", &"melee", &"control"],
		"costs": {"range_value": 3, "ap_cost": 1, "mp_cost": 0, "stamina_cost": 1, "aura_cost": 0, "cooldown_tu": 2, "hit_rate": 0},
		"targeting": {"target_mode": &"unit", "target_team_filter": &"enemy", "range_pattern": &"single", "area_pattern": &"single", "area_value": 0, "target_selection_mode": &"single_unit", "min_target_count": 1, "max_target_count": 1, "selection_order_mode": &"stable"},
		"mastery_curve": [24, 40, 62],
		"max_level": 3,
		"learn_source": &"book",
		"effect_defs": [{"kind": &"status", "status_id": &"taunted", "duration": 1, "power": 1}],
	},
	{
		"kind": &"active",
		"skill_id": &"warrior_war_cry",
		"display_name": "战吼",
		"description": "为近身盟友提供攻击增益。",
		"tags": [&"warrior", &"melee", &"support"],
		"costs": {"range_value": 0, "ap_cost": 2, "mp_cost": 0, "stamina_cost": 1, "aura_cost": 0, "cooldown_tu": 2, "hit_rate": 0},
		"targeting": {"target_mode": &"ground", "target_team_filter": &"ally", "range_pattern": &"single", "area_pattern": &"radius", "area_value": 1, "target_selection_mode": &"single_unit", "min_target_count": 1, "max_target_count": 1, "selection_order_mode": &"stable"},
		"mastery_curve": [24, 40, 62],
		"max_level": 3,
		"learn_source": &"book",
		"effect_defs": [{"kind": &"status", "status_id": &"attack_up", "duration": 1, "power": 1, "effect_target_team_filter": &"ally"}],
	},
	{
		"kind": &"active",
		"skill_id": &"warrior_true_dragon_slash",
		"display_name": "真龙斩",
		"description": "高代价直线终极范围技能。",
		"tags": [&"warrior", &"melee", &"aoe", &"finisher"],
		"costs": {"range_value": 4, "ap_cost": 3, "mp_cost": 0, "stamina_cost": 2, "aura_cost": 1, "cooldown_tu": 3, "hit_rate": 0},
		"targeting": {"target_mode": &"ground", "target_team_filter": &"enemy", "range_pattern": &"single", "area_pattern": &"line", "area_value": 4, "target_selection_mode": &"single_unit", "min_target_count": 1, "max_target_count": 1, "selection_order_mode": &"stable"},
		"mastery_curve": [30, 50, 78],
		"max_level": 3,
		"learn_source": &"book",
		"effect_defs": [{"kind": &"damage", "power": 18}],
	},
	{
		"kind": &"active",
		"skill_id": &"warrior_combo_strike",
		"display_name": "连击",
		"description": "圣剑连斩的来源技能之一。",
		"tags": [&"warrior", &"melee", &"combo"],
		"costs": {"range_value": 1, "ap_cost": 1, "mp_cost": 0, "stamina_cost": 1, "aura_cost": 0, "cooldown_tu": 1, "hit_rate": 0},
		"targeting": {"target_mode": &"unit", "target_team_filter": &"enemy", "range_pattern": &"single", "area_pattern": &"single", "area_value": 0, "target_selection_mode": &"single_unit", "min_target_count": 1, "max_target_count": 1, "selection_order_mode": &"stable"},
		"mastery_curve": [24, 40, 62, 90, 126],
		"max_level": 5,
		"learn_source": &"book",
		"effect_defs": [
			{"kind": &"damage", "power": 10},
			{"kind": &"status", "status_id": &"staggered", "duration": 1, "power": 1},
		],
	},
	{
		"kind": &"active",
		"skill_id": &"warrior_aura_slash",
		"display_name": "斗气斩",
		"description": "圣剑连斩的来源技能之一。",
		"tags": [&"warrior", &"melee", &"aura"],
		"costs": {"range_value": 3, "ap_cost": 2, "mp_cost": 0, "stamina_cost": 0, "aura_cost": 1, "cooldown_tu": 2, "hit_rate": 0},
		"targeting": {"target_mode": &"unit", "target_team_filter": &"enemy", "range_pattern": &"single", "area_pattern": &"single", "area_value": 0, "target_selection_mode": &"single_unit", "min_target_count": 1, "max_target_count": 1, "selection_order_mode": &"stable"},
		"mastery_curve": [24, 40, 62, 90, 126],
		"max_level": 5,
		"learn_source": &"book",
		"effect_defs": [{"kind": &"damage", "power": 12}],
	},
	{
		"kind": &"ground_variant",
		"skill_id": &"warrior_whirlwind_slash",
		"display_name": "旋风斩",
		"description": "冲锋与旋斩合并后的升级技能。",
		"tags": [&"warrior", &"melee", &"aoe", &"mobility"],
		"costs": {"range_value": 6, "ap_cost": 2, "mp_cost": 0, "stamina_cost": 2, "aura_cost": 1, "cooldown_tu": 3, "hit_rate": 0},
		"targeting": {"target_mode": &"ground", "target_team_filter": &"enemy", "range_pattern": &"single", "area_pattern": &"single", "area_value": 0, "target_selection_mode": &"single_unit", "min_target_count": 1, "max_target_count": 1, "selection_order_mode": &"stable"},
		"mastery_curve": [28, 46, 72],
		"max_level": 3,
		"learn_source": &"book",
		"learn_requirements": [&"charge", &"warrior_combo_strike"],
		"effect_defs": [],
		"custom": {
			"cast_variants": [
				{
					"variant_id": &"whirlwind_charge",
					"display_name": "旋风斩",
					"description": "兼容期内仍沿用冲锋选点，但额外挂出路径 AOE 的定义语义。",
					"min_skill_level": 0,
					"target_mode": &"ground",
					"footprint_pattern": &"single",
					"required_coord_count": 1,
					"allowed_base_terrains": [],
					"effect_defs": [
						{
							"kind": &"special",
							"effect_type": &"charge",
							"params": {
								"skill_id": "warrior_whirlwind_slash",
								"base_distance": 3,
								"distance_by_level": {"1": 4, "3": 5, "5": 6},
								"collision_base_damage": 10,
								"collision_size_gap_damage": 10,
							},
						},
						{
							"kind": &"special",
							"effect_type": &"path_step_aoe",
							"power": 10,
							"params": {
								"step_shape": "diamond",
								"step_radius": 1,
								"allow_repeat_hits_across_steps": true,
								"apply_on_successful_step_only": true,
							},
						},
					],
				},
			],
		},
	},
	{
		"kind": &"active",
		"skill_id": &"saint_blade_combo",
		"display_name": "圣剑连斩",
		"description": "连击与斗气斩的复合升级技能。当前仅在定义层记录循环追击与非破坏式合并语义。",
		"tags": [&"warrior", &"melee", &"combo", &"aura"],
		"costs": {"range_value": 1, "ap_cost": 2, "mp_cost": 0, "stamina_cost": 0, "aura_cost": 1, "cooldown_tu": 3, "hit_rate": 0},
		"targeting": {"target_mode": &"unit", "target_team_filter": &"enemy", "range_pattern": &"single", "area_pattern": &"single", "area_value": 0, "target_selection_mode": &"single_unit", "min_target_count": 1, "max_target_count": 1, "selection_order_mode": &"stable"},
		"mastery_curve": [30, 50, 78],
		"max_level": 3,
		"learn_source": &"book",
		"unlock_mode": &"composite_upgrade",
		"knowledge_requirements": [&"compania_family_legacy"],
		"skill_level_requirements": {
			"warrior_combo_strike": 5,
			"warrior_aura_slash": 5,
		},
		"achievement_requirements": [&"six_hit_combo"],
		"upgrade_source_skill_ids": [&"warrior_combo_strike", &"warrior_aura_slash"],
		"retain_source_skills_on_unlock": true,
		"core_skill_transition_mode": &"replace_sources_with_result",
		"effect_defs": [
			{"kind": &"damage", "power": 12},
			{
				"kind": &"special",
				"effect_type": &"repeat_attack_until_fail",
				"params": {
					"same_target_only": true,
					"base_hit_rate": 0,
					"follow_up_hit_rate_penalty": 10,
					"follow_up_damage_multiplier": 2,
					"follow_up_cost_multiplier": 2,
					"cost_resource": "aura",
					"stop_on_miss": true,
					"stop_on_insufficient_resource": true,
					"stop_on_target_down": true,
					"consume_cost_on_attempt": true,
					"damage_multiplier_stage": "pre_resistance",
				},
			},
		],
	},
]


static func get_specs() -> Array[Dictionary]:
	return WARRIOR_SKILL_SPECS.duplicate(true)
