## 文件说明：该脚本只提供弓箭手技能目录的声明式 spec 数据，不包含任何 builder 逻辑。
## 审查重点：重点核对 skill_id、display_name、description、tags、costs、targeting、mastery_curve、learn_source 与特殊 selection 语义是否完整保留。

class_name DesignSkillCatalogArcherSpecs
extends RefCounted

const ARCHER_SKILL_CATALOG_SPEC := {
	"catalog_id": &"archer",
	"display_name": "弓箭手",
	"description": "围绕中远距离点杀、牵制和区域火力展开的远程职业。",
	"skills": [
		{
			"kind": "active",
			"skill_id": &"archer_aimed_shot",
			"display_name": "精准射击",
			"description": "稳住呼吸后射出高精度一箭；若目标本回合尚未行动，则暴击率额外 `+15%`。",
			"tags": [&"archer", &"ranged", &"bow", &"output"],
			"costs": {
				"ap_cost": 1,
				"mp_cost": 0,
				"stamina_cost": 1,
				"aura_cost": 0,
				"cooldown_tu": 1,
				"hit_rate": 10,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 5,
				"area_pattern": &"single",
				"area_value": 0,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 13,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_armor_piercer",
			"display_name": "破甲箭",
			"description": "命中后附加破甲，作为后续集火开口。",
			"tags": [&"archer", &"ranged", &"bow", &"output"],
			"costs": {
				"ap_cost": 1,
				"mp_cost": 0,
				"stamina_cost": 1,
				"aura_cost": 0,
				"cooldown_tu": 2,
				"hit_rate": 0,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 5,
				"area_pattern": &"single",
				"area_value": 0,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 11,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
				{
					"kind": "status",
					"status_id": &"armor_break",
					"duration": 2,
					"power": 1,
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_heartseeker",
			"display_name": "追心箭",
			"description": "若目标已带有 `标记`，本次伤害改为 `150%`；若因此击杀，则返还 `1` 点 `stamina`。",
			"tags": [&"archer", &"ranged", &"bow", &"output"],
			"costs": {
				"ap_cost": 1,
				"mp_cost": 0,
				"stamina_cost": 1,
				"aura_cost": 0,
				"cooldown_tu": 2,
				"hit_rate": 5,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 5,
				"area_pattern": &"single",
				"area_value": 0,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 12,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_long_draw",
			"display_name": "满弦狙击",
			"description": "高蓄力狙杀技；若本回合已移动，则伤害降为 `135%`。",
			"tags": [&"archer", &"ranged", &"bow", &"output"],
			"costs": {
				"ap_cost": 2,
				"mp_cost": 0,
				"stamina_cost": 2,
				"aura_cost": 0,
				"cooldown_tu": 3,
				"hit_rate": 15,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 6,
				"area_pattern": &"single",
				"area_value": 0,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 16,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_split_bolt",
			"display_name": "裂风重矢",
			"description": "粗重箭矢沿直线贯穿最多 `2` 个敌人，适合打站位重叠目标。",
			"tags": [&"archer", &"ranged", &"bow", &"output"],
			"costs": {
				"ap_cost": 2,
				"mp_cost": 0,
				"stamina_cost": 2,
				"aura_cost": 0,
				"cooldown_tu": 2,
				"hit_rate": -5,
			},
			"targeting": {
				"target_mode": &"ground",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 5,
				"area_pattern": &"line",
				"area_value": 1,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 14,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_execution_arrow",
			"display_name": "猎手终结",
			"description": "根据目标已损失生命提高伤害；目标生命越低，终结收益越高。",
			"tags": [&"archer", &"ranged", &"bow", &"output"],
			"costs": {
				"ap_cost": 2,
				"mp_cost": 0,
				"stamina_cost": 2,
				"aura_cost": 0,
				"cooldown_tu": 3,
				"hit_rate": 0,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 5,
				"area_pattern": &"single",
				"area_value": 0,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 14,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_double_nock",
			"display_name": "双弦连射",
			"description": "连续射出两箭；第一箭未命中时不触发第二箭。",
			"tags": [&"archer", &"ranged", &"bow", &"output"],
			"costs": {
				"ap_cost": 2,
				"mp_cost": 0,
				"stamina_cost": 1,
				"aura_cost": 0,
				"cooldown_tu": 2,
				"hit_rate": 0,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 4,
				"area_pattern": &"single",
				"area_value": 0,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 7,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
				{
					"kind": "damage",
					"power": 7,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_far_horizon",
			"display_name": "天际远射",
			"description": "超远距离重箭；若自身处于 `预瞄` 或高地，则忽略命中惩罚。",
			"tags": [&"archer", &"ranged", &"bow", &"output"],
			"costs": {
				"ap_cost": 2,
				"mp_cost": 0,
				"stamina_cost": 0,
				"aura_cost": 1,
				"cooldown_tu": 3,
				"hit_rate": -10,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 7,
				"area_pattern": &"single",
				"area_value": 0,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 15,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_skirmish_step",
			"display_name": "游击步",
			"description": "向更安全的位置立即位移最多 `2` 格，并获得 `预瞄`，是弓箭手的基础转线手段。",
			"tags": [&"archer", &"ranged", &"bow", &"mobility"],
			"costs": {
				"ap_cost": 1,
				"mp_cost": 0,
				"stamina_cost": 1,
				"aura_cost": 0,
				"cooldown_tu": 1,
				"hit_rate": 0,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"ally",
				"range_pattern": &"single",
				"range_value": 0,
				"area_pattern": &"self",
				"area_value": 0,
				"target_selection_mode": &"self",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "status",
					"status_id": &"archer_pre_aim",
					"duration": 1,
					"power": 1,
				},
				{
					"kind": "forced_move",
					"distance": 2,
					"mode": &"retreat",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_backstep_shot",
			"display_name": "后跃射",
			"description": "先攻击再后撤 `2` 格；若后撤路径被阻挡，则只结算攻击。",
			"tags": [&"archer", &"ranged", &"bow", &"mobility"],
			"costs": {
				"ap_cost": 1,
				"mp_cost": 0,
				"stamina_cost": 1,
				"aura_cost": 0,
				"cooldown_tu": 2,
				"hit_rate": 5,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 4,
				"area_pattern": &"single",
				"area_value": 0,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 10,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_sidewind_slide",
			"display_name": "侧滑换位",
			"description": "攻击前或攻击后允许横向移动 `1` 格，用于避开直线冲锋或重构夹角。",
			"tags": [&"archer", &"ranged", &"bow", &"mobility"],
			"costs": {
				"ap_cost": 1,
				"mp_cost": 0,
				"stamina_cost": 1,
				"aura_cost": 0,
				"cooldown_tu": 2,
				"hit_rate": 0,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 4,
				"area_pattern": &"single",
				"area_value": 0,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 10,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_running_shot",
			"display_name": "奔袭射击",
			"description": "若本回合先移动至少 `3` 格，则取消命中惩罚，并额外施加 `标记`。",
			"tags": [&"archer", &"ranged", &"bow", &"mobility"],
			"costs": {
				"ap_cost": 1,
				"mp_cost": 0,
				"stamina_cost": 1,
				"aura_cost": 0,
				"cooldown_tu": 1,
				"hit_rate": -5,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 4,
				"area_pattern": &"single",
				"area_value": 0,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 11,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_grapple_redeploy",
			"display_name": "索钩转位",
			"description": "牵引至高地、障碍物边缘或己方布置点附近；转位后下一个弓技射程 `+1`。",
			"tags": [&"archer", &"ranged", &"bow", &"mobility"],
			"costs": {
				"ap_cost": 1,
				"mp_cost": 0,
				"stamina_cost": 1,
				"aura_cost": 0,
				"cooldown_tu": 3,
				"hit_rate": 0,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"ally",
				"range_pattern": &"single",
				"range_value": 4,
				"area_pattern": &"self",
				"area_value": 0,
				"target_selection_mode": &"self",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "status",
					"status_id": &"archer_range_up",
					"duration": 1,
					"power": 1,
					"effect_target_team_filter": &"ally",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_evasive_roll",
			"display_name": "翻滚卸力",
			"description": "向更安全的位置位移 `2` 格，并获得直到回合结束的 `闪避 +20%`，适合脱离贴身威胁。",
			"tags": [&"archer", &"ranged", &"bow", &"mobility"],
			"costs": {
				"ap_cost": 1,
				"mp_cost": 0,
				"stamina_cost": 1,
				"aura_cost": 0,
				"cooldown_tu": 2,
				"hit_rate": 0,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"ally",
				"range_pattern": &"single",
				"range_value": 0,
				"area_pattern": &"self",
				"area_value": 0,
				"target_selection_mode": &"self",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "status",
					"status_id": &"evasion_up",
					"duration": 1,
					"power": 1,
				},
				{
					"kind": "forced_move",
					"distance": 2,
					"mode": &"retreat",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_highground_claim",
			"display_name": "抢高位",
			"description": "向指定高低差合法格位移动最多 `3` 格；若落点为高地，额外获得 `预瞄`。",
			"tags": [&"archer", &"ranged", &"bow", &"mobility"],
			"costs": {
				"ap_cost": 2,
				"mp_cost": 0,
				"stamina_cost": 2,
				"aura_cost": 0,
				"cooldown_tu": 3,
				"hit_rate": 0,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"ally",
				"range_pattern": &"single",
				"range_value": 3,
				"area_pattern": &"self",
				"area_value": 0,
				"target_selection_mode": &"self",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "status",
					"status_id": &"archer_pre_aim",
					"duration": 1,
					"power": 1,
					"effect_target_team_filter": &"ally",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_hunter_feint",
			"display_name": "猎步佯退",
			"description": "轻伤试探并附加 `标记`；命中后可免费移动 `1` 格。",
			"tags": [&"archer", &"ranged", &"bow", &"mobility"],
			"costs": {
				"ap_cost": 1,
				"mp_cost": 0,
				"stamina_cost": 1,
				"aura_cost": 0,
				"cooldown_tu": 2,
				"hit_rate": 0,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 4,
				"area_pattern": &"single",
				"area_value": 0,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 8,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_pinning_shot",
			"display_name": "钉射",
			"description": "单体伤害并施加 pinned。",
			"tags": [&"archer", &"ranged", &"bow", &"control"],
			"costs": {
				"ap_cost": 1,
				"mp_cost": 0,
				"stamina_cost": 1,
				"aura_cost": 0,
				"cooldown_tu": 2,
				"hit_rate": 0,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 4,
				"area_pattern": &"single",
				"area_value": 0,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 10,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
				{
					"kind": "status",
					"status_id": &"pinned",
					"duration": 1,
					"power": 1,
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_tendon_splitter",
			"display_name": "断筋箭",
			"description": "命中后施加 `断筋`；对依赖冲锋和突进的敌人压制力很强。",
			"tags": [&"archer", &"ranged", &"bow", &"control"],
			"costs": {
				"ap_cost": 1,
				"mp_cost": 0,
				"stamina_cost": 1,
				"aura_cost": 0,
				"cooldown_tu": 2,
				"hit_rate": -5,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 5,
				"area_pattern": &"single",
				"area_value": 0,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 9,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_disrupting_arrow",
			"display_name": "扰咒箭",
			"description": "命中后令目标下一次技能消耗 `+1`，并使其施法类动作命中 `-15%`。",
			"tags": [&"archer", &"ranged", &"bow", &"control"],
			"costs": {
				"ap_cost": 1,
				"mp_cost": 0,
				"stamina_cost": 1,
				"aura_cost": 0,
				"cooldown_tu": 3,
				"hit_rate": 5,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 5,
				"area_pattern": &"single",
				"area_value": 0,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 8,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_flash_whistle",
			"display_name": "炫目鸣镝",
			"description": "爆出刺耳鸣响，范围内敌人获得 `命中 -15%` 且失去反击资格，持续 `1` 回合。",
			"tags": [&"archer", &"ranged", &"bow", &"control"],
			"costs": {
				"ap_cost": 2,
				"mp_cost": 0,
				"stamina_cost": 2,
				"aura_cost": 0,
				"cooldown_tu": 3,
				"hit_rate": 0,
			},
			"targeting": {
				"target_mode": &"ground",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 5,
				"area_pattern": &"radius",
				"area_value": 1,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 7,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_tripwire_arrow",
			"display_name": "绊索箭",
			"description": "在直线 `3` 格上布置绊索带；首个穿过的敌人立即停止移动并获得 `压制`。",
			"tags": [&"archer", &"ranged", &"bow", &"control"],
			"costs": {
				"ap_cost": 1,
				"mp_cost": 0,
				"stamina_cost": 1,
				"aura_cost": 0,
				"cooldown_tu": 2,
				"hit_rate": 0,
			},
			"targeting": {
				"target_mode": &"ground",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 4,
				"area_pattern": &"line",
				"area_value": 1,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 6,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_shield_breaker",
			"display_name": "破盾箭",
			"description": "对处于格挡、护卫或防御姿态的目标追加 `+25%` 伤害，并移除其防御姿态。",
			"tags": [&"archer", &"ranged", &"bow", &"control"],
			"costs": {
				"ap_cost": 1,
				"mp_cost": 0,
				"stamina_cost": 1,
				"aura_cost": 0,
				"cooldown_tu": 2,
				"hit_rate": -5,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 5,
				"area_pattern": &"single",
				"area_value": 0,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 10,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_fearsignal_shot",
			"display_name": "惊禽哨箭",
			"description": "扇形压制射击，命中敌人获得 `压制`；若目标本就带有 `标记`，额外后退 `1` 格。",
			"tags": [&"archer", &"ranged", &"bow", &"control"],
			"costs": {
				"ap_cost": 2,
				"mp_cost": 0,
				"stamina_cost": 2,
				"aura_cost": 0,
				"cooldown_tu": 3,
				"hit_rate": 0,
			},
			"targeting": {
				"target_mode": &"ground",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 5,
				"area_pattern": &"cone",
				"area_value": 1,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 8,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_harrier_mark",
			"display_name": "猎印追缉",
			"description": "纯功能技能，给目标施加强化版 `标记` `2` 回合；所有友军远程攻击对此目标命中 `+10%`。",
			"tags": [&"archer", &"ranged", &"bow", &"control"],
			"costs": {
				"ap_cost": 1,
				"mp_cost": 0,
				"stamina_cost": 1,
				"aura_cost": 0,
				"cooldown_tu": 2,
				"hit_rate": 10,
			},
			"targeting": {
				"target_mode": &"unit",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 5,
				"area_pattern": &"single",
				"area_value": 0,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "status",
					"status_id": &"marked",
					"duration": 2,
					"power": 1,
				},
			],
		},
		{
			"kind": "ground_variant",
			"skill_id": &"archer_multishot",
			"display_name": "连珠箭",
			"description": "通过依次锁定多个目标来铺开点杀火力，是弓箭手的招牌多目标技能。",
			"tags": [&"archer", &"ranged", &"bow", &"aoe"],
			"costs": {
				"ap_cost": 2,
				"mp_cost": 0,
				"stamina_cost": 2,
				"aura_cost": 0,
				"cooldown_tu": 2,
				"hit_rate": -5,
			},
			"targeting": {
				"target_mode": &"ground",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 5,
				"area_pattern": &"single",
				"area_value": 0,
				"target_selection_mode": &"multi_unit",
				"min_target_count": 2,
				"max_target_count": 3,
				"selection_order_mode": &"manual",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [],
			"custom": {
				"cast_variants": [
					{
						"variant_id": &"multishot_volley",
						"display_name": "连珠箭",
						"description": "依次锁定 2 到 3 个不同敌方目标格，并按选择顺序逐个结算射击。",
						"min_skill_level": 0,
						"footprint_pattern": &"unordered",
						"required_coord_count": 3,
						"allowed_base_terrains": [],
						"effect_defs": [
							{
								"kind": "damage",
								"power": 8,
								"scaling_attribute_id": &"physical_attack",
								"defense_attribute_id": &"physical_defense",
							},
						],
					},
				],
				"ai_tags": [&"multi_target", &"focus_fire"],
			},
		},
		{
			"kind": "active",
			"skill_id": &"archer_arrow_rain",
			"display_name": "箭雨",
			"description": "标准范围火力；命中的敌人额外获得 `压制`，适合拆散抱团站位。",
			"tags": [&"archer", &"ranged", &"bow", &"aoe"],
			"costs": {
				"ap_cost": 2,
				"mp_cost": 0,
				"stamina_cost": 2,
				"aura_cost": 0,
				"cooldown_tu": 3,
				"hit_rate": -10,
			},
			"targeting": {
				"target_mode": &"ground",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 5,
				"area_pattern": &"radius",
				"area_value": 1,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 8,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
				{
					"kind": "status",
					"status_id": &"pinned",
					"duration": 1,
					"power": 1,
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_fan_volley",
			"display_name": "扇幕齐射",
			"description": "中距离扇面清线技，对近距离多前排组合威胁较高。",
			"tags": [&"archer", &"ranged", &"bow", &"aoe"],
			"costs": {
				"ap_cost": 2,
				"mp_cost": 0,
				"stamina_cost": 2,
				"aura_cost": 0,
				"cooldown_tu": 2,
				"hit_rate": 0,
			},
			"targeting": {
				"target_mode": &"ground",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 4,
				"area_pattern": &"cone",
				"area_value": 1,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 9,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_suppressive_fire",
			"display_name": "压制射击",
			"description": "对一条直线区域持续覆盖；被命中的敌人获得 `压制`，该路径在下回合前移动成本 `+1`。",
			"tags": [&"archer", &"ranged", &"bow", &"aoe"],
			"costs": {
				"ap_cost": 2,
				"mp_cost": 0,
				"stamina_cost": 2,
				"aura_cost": 0,
				"cooldown_tu": 3,
				"hit_rate": 0,
			},
			"targeting": {
				"target_mode": &"ground",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 5,
				"area_pattern": &"line",
				"area_value": 1,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 7,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_breach_barrage",
			"display_name": "贯阵齐发",
			"description": "高阶穿阵技，直线上的每命中一个敌人，下一名目标额外承受 `+10%` 伤害。",
			"tags": [&"archer", &"ranged", &"bow", &"aoe"],
			"costs": {
				"ap_cost": 2,
				"mp_cost": 0,
				"stamina_cost": 2,
				"aura_cost": 1,
				"cooldown_tu": 4,
				"hit_rate": -10,
			},
			"targeting": {
				"target_mode": &"ground",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 6,
				"area_pattern": &"line",
				"area_value": 1,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 12,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_blast_arrow",
			"display_name": "爆裂箭",
			"description": "在落点爆开冲击；对轻型掩体、召唤物或低护甲后排有较高压制价值。",
			"tags": [&"archer", &"ranged", &"bow", &"aoe"],
			"costs": {
				"ap_cost": 2,
				"mp_cost": 0,
				"stamina_cost": 0,
				"aura_cost": 1,
				"cooldown_tu": 3,
				"hit_rate": 0,
			},
			"targeting": {
				"target_mode": &"ground",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 5,
				"area_pattern": &"radius",
				"area_value": 1,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 10,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_hunting_grid",
			"display_name": "狩猎网阵",
			"description": "在区域内撒布索绳与短箭；敌人首次离开区域时再受一次 `50%` 伤害并获得 `断筋`。",
			"tags": [&"archer", &"ranged", &"bow", &"aoe"],
			"costs": {
				"ap_cost": 3,
				"mp_cost": 0,
				"stamina_cost": 0,
				"aura_cost": 1,
				"cooldown_tu": 4,
				"hit_rate": 0,
			},
			"targeting": {
				"target_mode": &"ground",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 4,
				"area_pattern": &"radius",
				"area_value": 2,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 6,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
		{
			"kind": "active",
			"skill_id": &"archer_killing_field",
			"display_name": "猎场封锁",
			"description": "招牌领域技；区域持续 `2` 回合，敌人每次在其中结束行动时受到追击伤害并自动附加 `标记`。",
			"tags": [&"archer", &"ranged", &"bow", &"aoe"],
			"costs": {
				"ap_cost": 3,
				"mp_cost": 0,
				"stamina_cost": 0,
				"aura_cost": 2,
				"cooldown_tu": 5,
				"hit_rate": -10,
			},
			"targeting": {
				"target_mode": &"ground",
				"target_team_filter": &"enemy",
				"range_pattern": &"single",
				"range_value": 5,
				"area_pattern": &"radius",
				"area_value": 2,
				"target_selection_mode": &"single_unit",
				"min_target_count": 1,
				"max_target_count": 1,
				"selection_order_mode": &"stable",
			},
			"mastery_curve": [28, 46, 72],
			"max_level": 3,
			"learn_source": &"book",
			"effect_defs": [
				{
					"kind": "damage",
					"power": 7,
					"scaling_attribute_id": &"physical_attack",
					"defense_attribute_id": &"physical_defense",
				},
			],
		},
	],
}


static func get_specs() -> Array[Dictionary]:
	var skills: Array[Dictionary] = []
	for skill_variant in ARCHER_SKILL_CATALOG_SPEC.get("skills", []):
		if skill_variant is Dictionary:
			skills.append(skill_variant)
	return skills

