#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using Godot;

public partial class run_trait_json_content_regression : LifecycleTestSceneTree
{
    private const int ExpectedTraitCount = 239;
    private const string TrackedJsonPath = "res://data/configs/json/traits/traits.json";
    private const string TrackedSchemaPath = "res://data/schemas/content/traits.schema.json";
    private const string RuleInventoryPath = "res://tests/progression/fixtures/trait_validator_diagnostic_golden/rule_inventory.tsv";
    private const string DiagnosticGoldenPath = "res://tests/progression/fixtures/trait_validator_diagnostic_golden/exact_diagnostic_golden.tsv";
    private const string InvalidFixtureDirectory = "res://tests/progression/fixtures/trait_validator_diagnostic_golden";

    private readonly TestHarness _test = new();

    public override void _Initialize() => RunAfterProcessStartup(Run);

    private void Run()
    {
        try
        {
            string canonicalJson = ReadUtf8(TrackedJsonPath);
            string schema = new ContentJsonSchemaExporter().Export(
                TraitContentJsonAuthoringDomain.SchemaRegistration
            );
            string inventory = BuildRuleInventory();
            string diagnosticGolden = BuildDiagnosticGolden();

            AssertCanonicalJson(canonicalJson);
            AssertPureContracts();
            AssertRoundTrip(canonicalJson);
            _test.Eq(TraitValidationRules.Inventory.Count, 49, "trait import boundary pins 49 strict DTO/domain rules");

            if (OS.GetEnvironment("MAGIC_TRAIT_JSON_EMIT") == "1")
                EmitArtifacts(canonicalJson, schema, inventory, diagnosticGolden);
            else
            {
                _test.Eq(ReadUtf8(TrackedSchemaPath), schema, "tracked trait schema must be generated byte-exact");
                _test.Eq(ReadUtf8(RuleInventoryPath), inventory, "trait validator rule inventory must be byte-exact");
                _test.Eq(ReadUtf8(DiagnosticGoldenPath), diagnosticGolden, "invalid trait JSON diagnostics must match exact golden");
                AssertProductionRegistry();
            }
        }
        catch (Exception exception)
        {
            _test.Fail($"Unexpected trait JSON content exception: {exception}");
        }

        RequestTestExit(_test.Finish("Trait JSON content regression"));
    }

    private void AssertCanonicalJson(string canonicalJson)
    {
        ContentImportBatch<TraitImportModel> batch =
            TraitContentJsonAuthoringDomain.CreateImportDescriptor(
                "memory://canonical-traits",
                new SingleSourceReader(new ContentJsonSourceText("traits.json", canonicalJson))
            ).Import();
        _test.Eq(batch.Diagnostics.Count, 0, $"tracked trait JSON imports cleanly: {Format(batch.Diagnostics)}");
        _test.Eq(batch.Entries.Count, ExpectedTraitCount, "tracked JSON pins the formal trait baseline");
        IReadOnlyList<TraitImportModel> imports = batch.Entries
            .Select(value => value.Import)
            .ToArray();
        string rewritten = TraitImportCanonicalJson.WriteDocument(
            new ContentCanonicalJsonWriter(),
            "all",
            imports
        );
        _test.Eq(canonicalJson, rewritten, "tracked trait JSON must remain canonical byte-exact");
        _test.True(canonicalJson.Contains("\"trait_id\": \"gear_set.", StringComparison.Ordinal), "canonical JSON preserves dotted trait IDs");
    }

    private void AssertRoundTrip(string canonicalJson)
    {
        ContentImportBatch<TraitImportModel> batch =
            TraitContentJsonAuthoringDomain.CreateImportDescriptor(
                "memory://traits",
                new SingleSourceReader(new ContentJsonSourceText("traits.json", canonicalJson))
            ).Import();
        _test.Eq(batch.Diagnostics.Count, 0, $"canonical trait JSON reimports cleanly: {Format(batch.Diagnostics)}");
        _test.Eq(batch.Entries.Count, ExpectedTraitCount, "canonical round-trip retains all traits");
        _test.Eq(batch.Entries.Select(value => value.Import.TraitId).Distinct(StringComparer.Ordinal).Count(), ExpectedTraitCount, "round-trip trait IDs remain unique");
        _test.False(
            batch.Entries.SelectMany(value => EnumerateSaveTags(value.Import)).Any(HasRemovedSaveTagSuffix),
            "canonical save-tag fields do not retain removed semantic suffix syntax"
        );
        foreach (ContentImportEntry<TraitImportModel> entry in batch.Entries)
            _test.Eq(TraitDefinitionProjector.Project(entry.Import).TraitId.ToString(), entry.Import.TraitId, $"definition projector preserves {entry.Import.TraitId}");

        ContentImportBatch<TraitImportModel> invalidDto =
            TraitContentJsonAuthoringDomain.CreateImportDescriptor(
                "memory://invalid-traits",
                new SingleSourceReader(
                    new ContentJsonSourceText(
                        "invalid.json",
                        "{\"schema\":1,\"domain\":\"traits\",\"family\":\"invalid\",\"templates\":{},\"entries\":[{\"trait_id\":\"missing_fields\"}]}"
                    )
                )
            ).Import();
        _test.True(
            invalidDto.Diagnostics.Any(value => value.RuleId == TraitJsonImportRules.InvalidDto),
            "strict DTO rejects missing required trait fields"
        );

        if (batch.Entries.Count > 0)
        {
            TraitImportModel valid = batch.Entries[0].Import;
            var suffixCase = new TraitImportModel(
                valid.TraitId, valid.DisplayName, valid.Description, valid.Categories,
                valid.AllowedSourceKinds, valid.EffectType, valid.TriggerType, valid.StackPolicy,
                valid.ChargeScope, valid.ChargeResetTiming, valid.HighestRollCompareKey,
                valid.VisionRange, valid.ProficiencyChoiceCount, valid.AttributeModifiers,
                valid.SaveAdvantageTags, valid.SaveDisadvantageTags, new[] { "sleep_immunity" },
                valid.DamageResistanceEntries, valid.SaveBonusEntries, valid.PassiveStatusEffects,
                valid.RollValueSchema
            );
            IReadOnlyList<ContentJsonDiagnostic> suffixDiagnostics = new TraitImportModelValidator()
                .ValidateDomainLocal(
                    new JsonContentEntryContext("traits", suffixCase.TraitId, "suffix.json#fixture", "/entries/0"),
                    suffixCase
                );
            _test.True(
                suffixDiagnostics.Any(value => value.RuleId == TraitValidationRules.SaveTagBare),
                "validator rejects removed *_immunity suffix and requires the bare save tag"
            );
        }
    }

    private static IEnumerable<string> EnumerateSaveTags(TraitImportModel import)
    {
        foreach (string value in import.SaveAdvantageTags)
            yield return value;
        foreach (string value in import.SaveDisadvantageTags)
            yield return value;
        foreach (string value in import.SaveImmunityTags)
            yield return value;
        foreach (TraitPassiveStatusEffectImportModel status in import.PassiveStatusEffects)
        {
            foreach (string value in status.SaveImmunityTags)
                yield return value;
        }
    }

    private static bool HasRemovedSaveTagSuffix(string value) =>
        value.EndsWith("_advantage", StringComparison.Ordinal)
        || value.EndsWith("_disadvantage", StringComparison.Ordinal)
        || value.EndsWith("_immunity", StringComparison.Ordinal);

    private void AssertProductionRegistry()
    {
        using var registry = new TraitContentRegistry();
        IReadOnlyList<string> errors = registry.Validate();
        _test.Eq(errors.Count, 0, $"production TraitContentRegistry loads JSON directly: {string.Join(" | ", errors)}");
        IReadOnlyDictionary<StringName, TraitDefinition> definitions = registry.GetTraitDefsTyped();
        _test.Eq(definitions.Count, ExpectedTraitCount, "production registry exposes all JSON traits");
        _test.True(definitions.Keys.Any(value => value.ToString().Contains('.', StringComparison.Ordinal)), "production registry preserves dotted trait IDs");
    }

    private void AssertPureContracts()
    {
        AssertTypeGraphHasNoResource(typeof(TraitJsonDto), new HashSet<Type>());
        AssertTypeGraphHasNoResource(typeof(TraitImportModel), new HashSet<Type>());
        foreach (PropertyInfo property in typeof(TraitDefinition).GetProperties(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
            _test.False(typeof(Resource).IsAssignableFrom(Unwrap(property.PropertyType)), $"TraitDefinition property {property.Name} must not carry Resource/source ownership");
        foreach (MethodInfo method in typeof(TraitDefinition).GetMethods(BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly))
        {
            _test.False(typeof(Resource).IsAssignableFrom(Unwrap(method.ReturnType)), $"TraitDefinition method {method.Name} must not return Resource/source ownership");
            foreach (ParameterInfo parameter in method.GetParameters())
                _test.False(typeof(Resource).IsAssignableFrom(Unwrap(parameter.ParameterType)), $"TraitDefinition method {method.Name} must not accept Resource/source ownership");
        }
        foreach (ConstructorInfo constructor in typeof(TraitDefinition).GetConstructors(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
        {
            foreach (ParameterInfo parameter in constructor.GetParameters())
                _test.False(typeof(Resource).IsAssignableFrom(Unwrap(parameter.ParameterType)), "TraitDefinition constructor must not accept Resource/source ownership");
        }
    }

    private void AssertTypeGraphHasNoResource(Type type, HashSet<Type> visited)
    {
        if (!visited.Add(type))
            return;
        _test.False(typeof(Resource).IsAssignableFrom(type), $"trait DTO/import graph must not contain Resource type {type.FullName}");
        foreach (PropertyInfo property in type.GetProperties(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
        {
            Type child = Unwrap(property.PropertyType);
            if (child == typeof(string) || child.IsPrimitive || child.IsEnum)
                continue;
            if (child.Assembly == typeof(TraitImportModel).Assembly)
                AssertTypeGraphHasNoResource(child, visited);
        }
    }

    private static Type Unwrap(Type type)
    {
        if (type.IsArray)
            return type.GetElementType() ?? type;
        if (type.IsGenericType)
            return type.GetGenericArguments().Last();
        return Nullable.GetUnderlyingType(type) ?? type;
    }

    private static string BuildRuleInventory()
    {
        var text = new StringBuilder("rule_id\tdescription\n");
        foreach (TraitValidationRuleSpec rule in TraitValidationRules.Inventory)
            text.Append(rule.RuleId).Append('\t').Append(rule.Description).Append('\n');
        return text.ToString();
    }

    private static string BuildDiagnosticGolden()
    {
        ContentImportBatch<TraitImportModel> batch =
            TraitContentJsonAuthoringDomain.CreateImportDescriptor(
                InvalidFixtureDirectory,
                new GodotContentJsonSourceReader()
            ).Import();
        var diagnostics = new List<ContentJsonDiagnostic>(batch.Diagnostics);
        diagnostics.Sort((left, right) =>
        {
            int result = StringComparer.Ordinal.Compare(left.SourceLabel, right.SourceLabel);
            if (result != 0) return result;
            result = StringComparer.Ordinal.Compare(left.JsonPointer, right.JsonPointer);
            if (result != 0) return result;
            return StringComparer.Ordinal.Compare(left.RuleId, right.RuleId);
        });
        var text = new StringBuilder("rule_id\tsource\tpointer\tmessage\n");
        foreach (ContentJsonDiagnostic diagnostic in diagnostics)
        {
            text.Append(diagnostic.RuleId).Append('\t')
                .Append(diagnostic.SourceLabel).Append('\t')
                .Append(diagnostic.JsonPointer).Append('\t')
                .Append(diagnostic.Message.Replace('\t', ' ').Replace('\r', ' ').Replace('\n', ' '))
                .Append('\n');
        }
        return text.ToString();
    }

    private static void EmitArtifacts(string json, string schema, string inventory, string golden)
    {
        Emit("TRAITS_JSON_BASE64=", json);
        Emit("TRAIT_SCHEMA_BASE64=", schema);
        Emit("TRAIT_RULE_INVENTORY_BASE64=", inventory);
        Emit("TRAIT_DIAGNOSTIC_GOLDEN_BASE64=", golden);
    }

    private static void Emit(string prefix, string value) =>
        ConsoleProcessOutput.WriteStandard(prefix, Convert.ToBase64String(Encoding.UTF8.GetBytes(value)));

    private static string ReadUtf8(string path)
    {
        using FileAccess file = FileAccess.Open(path, FileAccess.ModeFlags.Read);
        if (file == null)
            throw new InvalidOperationException($"Could not open tracked trait artifact {path}.");
        return file.GetAsText(skipCr: false);
    }

    private static string Format(IReadOnlyList<ContentJsonDiagnostic> diagnostics) =>
        string.Join(" | ", diagnostics.Select(value => $"{value.RuleId}@{value.SourceLabel}{value.JsonPointer}: {value.Message}"));

    private sealed class SingleSourceReader : IContentJsonSourceReader
    {
        private readonly IReadOnlyList<ContentJsonSourceText> _sources;

        internal SingleSourceReader(ContentJsonSourceText source) => _sources = new[] { source };

        public IReadOnlyList<ContentJsonSourceText> ReadUtf8Documents(string directoryPath) => _sources;
    }
}
